### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'current_team_id' in 'field list'

### ISSUE THREAD

**Issue by devhoussam1998** [stephenjude/filament-jetstream#1]
### What happened?

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'current_team_id' in 'field list'

### How to reproduce the bug

After I install the package in fresh laravel application i setup everything correctly once I create a new team I get:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'current_team_id' in 'field list'

<img width="1620" alt="Screenshot 2024-03-04 at 11 21 46" src="https://github.com/stephenjude/filament-jetstream/assets/121255432/a9cdbd90-62b2-4d38-a73f-1a35b18d1d5e">

### Package Version

0.0.6

### PHP Version

8.1

### Laravel Version

10.10

### Which operating systems does with happen with?

macOS

**Comment by stephenjude** [comment]
@devhoussam1998 I wasn't able to replicate this issue. I just installed and run migrations again to be sure all tables are go to go. Everything works fine. 

Can you check the user's table to be sure your migration file contains the `current_team_id` column. 

If the column exists please rerun the installation command and and run the migration afresh.
