### ISSUE TITLE
[Bug]: User Profile Doesn’t open

### ISSUE THREAD

**Issue by repzlaw** [stephenjude/filament-jetstream#11]
### What happened?

I cannot currently navigate to the user profile from the nav menu after installation. It Routes me back to the dashboard.
Please can you fix this?

### How to reproduce the bug

After download, Try to navigate to the user dashboard

### Package Version

0.0.10

### PHP Version

8.3

### Laravel Version

11

**Comment by repzlaw** [comment]
I think the issue comes when email is not verified. 
Sorry about this

**Comment by lpcs007** [comment]
new project, email is verified and same issue. any idea when will be fixed?

**Comment by stephenjude** [comment]
Not sure why this is happening.

Can you try and reproduce this error a new project in a public repo? @lpcs007
