### ISSUE TITLE
[Bug]: Creating a New User Results in Creation of Two Teams

### ISSUE THREAD

**Issue by D4ve-R** [stephenjude/filament-jetstream#12]
### What happened?

When a new user is created in a fresh installed application, the system unexpectedly creates two teams for the user instead of one.  
  
<img width="1088" alt="Bildschirmfoto 2024-06-09 um 15 14 08" src="https://github.com/stephenjude/filament-jetstream/assets/69651599/d2598e36-2092-4425-bcc6-a470bae294b9">

### How to reproduce the bug

* Fresh install
* register new user

### Package Version

0.0.10

### PHP Version

8.3.7

### Laravel Version

11.10.0

### Which operating systems does with happen with?

macOS

**Comment by danpalmieri** [comment]
This is happening to me too.

**Comment by D4ve-R** [comment]
I think this might be a bug in filament itself

**Comment by stephenjude** [comment]
It seems that both Filament and this package are creating a default team for every registered user. I've disabled the team creation feature for this package, which appears to have resolved the issue. 
Commit: https://github.com/stephenjude/filament-jetstream/commit/6ac19af9081355ef22462b453e90019625588016
Cc: @D4ve-R @danpalmieri
