### ISSUE TITLE
[Bug]: It's not a bug, I ask for help

### ISSUE THREAD

**Issue by virla01** [stephenjude/filament-jetstream#17]
### What happened?

Hi, I'm a newbie to Filament, and I installed the plugin according to the documentation, but I don't see that it does anything. I imagine that you have to put something inside the panel file, but they don't explain how to do that. Could you help me with that?
Thanks

### How to reproduce the bug

does nothing, a new menu appears

### Package Version

0.0.13

### PHP Version

8.3.11

### Laravel Version

11

### Which operating systems does with happen with?

Windows

### Notes

Sorry, but I was looking for how to do it, and nothing came up.

**Comment by drsdre** [comment]
Did you run the following command?
`php artisan filament:jetstream:install --teams --api`

(remove --teams and/or --api if this functionality is needed)

**Comment by dtremp007** [comment]
If you already have installed filament, and then run the commands in the README, you will end up generating two different panels. This library uses "/app" as the route name, and the default is `/admin`. Check `~/app/Providers/Filament`
