### ISSUE TITLE
[Bug]: Links in GitHub 'Issues' are broken

### ISSUE THREAD

**Issue by drsdre** [stephenjude/filament-jetstream#18]
### What happened?

From the 'New Issue' screen in this Github, the links for  'Ask a question' and 'Request a feature' lead to a Github 404 page.

### How to reproduce the bug

On https://github.com/stephenjude/filament-jetstream/issues click 'New Issue'.
From https://github.com/stephenjude/filament-jetstream/issues/new/choose click on 'Open' button of 'Ask a question'.
This leads to https://github.com/stephenjude/filament-jetstream/discussions/new?category=q-a which is a 404 page.

Same for 'Request a feature'.

### Package Version

2.0.0

### PHP Version

8.2.0

### Laravel Version

11.0

**Comment by stephenjude** [comment]
I have confirmed this @drsdre, I think we can discuss via issues as I can't find the discussion feature for this repository.
