### ISSUE TITLE
[QA]: Use Jetstream feature tests for login/register

### ISSUE THREAD

**Issue by drsdre** [stephenjude/filament-jetstream#19]
### What happened?

I would like to keep using the existing published feature tests for Jetstream (https://github.com/laravel/jetstream/tree/80543f7f19f3e5c587bee62d2b76d6699b101052/stubs/tests). I adjusted the URL's to use /app  in the AuthenticationTest 'users can authenticate using the login screen' and RegistrationTest 'new users can register'.  However the post does not seem to work for the Filament Jetstream login and registration page.

### How to reproduce the bug

Install the Jetstream test stubs and run them.

### Package Version

0.0.13

### PHP Version

8.2

### Laravel Version

11.0

### Which operating systems does with happen with?

macOS

**Comment by stephenjude** [comment]
@drsdre, the registration and login features of this package are all from @filamentphp and not Laravel Jetstream auth which means that the Laravel Jetstream auth tests won't work using this package.
