### ISSUE TITLE
[Bug]: Can't use 2FA, login challenge not showing up

### ISSUE THREAD

**Issue by bizr** [stephenjude/filament-jetstream#20]
### What happened?

When I enable 2FA, I log-in but 2FA challenge is not showing, I am presented with the panel.

### How to reproduce the bug

1. Install the plug-in on a fresh installation
2. Create a new filament user
3. Log-in with the user and enable 2FA with Google Authenticator
4. Log-out
5. when I log-in, I am presented with the panel without 2FA being asked

### Package Version

0.0.13

### PHP Version

8.3.11

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by stephenjude** [comment]
@bizr here is the solution to the 2FA solution that can fix this — https://github.com/stephenjude/filament-two-factor-authentication

I am still working on a fix for this package.

**Comment by lbitoy** [comment]
> @bizr here is the solution to the 2FA solution that can fix this — https://github.com/stephenjude/filament-two-factor-authentication
> 
> I am still working on a fix for this package.

Hi @stephenjude  this was marked as closed, but was this fixed in the current release?

**Comment by stephenjude** [comment]
No, I am currently reworking the whole package and this release will come with inbuilt 2FA feature just like Laravel Jetstream

**Comment by Sophist-UK** [comment]
@stephenjude I have included this package in my project as I want to combine the comprehensiveness of the Jetstream authentication functionality (Livewire supported email verification, 2FA, Teams, etc.) with Filament - which seems to be the aim of this project.

And I was imagining that it should be easily possible to make them work together with a few small tweaks - not needing a major rewrite of e.g. 2FA. But apparently it isn't quite that easy!!

Can you explain what difficulties faced to make them work together?
