### ISSUE TITLE
[Bug]: Page Freeze

### ISSUE THREAD

**Issue by Gjentii** [stephenjude/filament-jetstream#25]
### What happened?

Page freezes and background becomes dark

### How to reproduce the bug

When a modal opens it the background becomes dark and the page screen freezes. Its happening to the modals of the actions that are linked  with the table method

### Package Version

latest

### PHP Version

8.3

### Laravel Version

10

**Comment by hazbu** [comment]
Try composer update to upgrade your filament and laravel
